# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='_book',
        ),
        migrations.AddField(
            model_name='book',
            name='_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Author'),
            preserve_default=False,
        ),
    ]
